#!/usr/bin/env python3
"""Checks on the Android link that origin's own scripts cannot know to make.

    check_link.py --elf emerald3ds.elf --span-header boot_span.h
    check_link.py --elf emerald3ds.elf --image build/gamedata_image.elf \
        --load-address 0x04000000 --ndk-lib DIR --lib -lc ... [--allow-undefined]

- The library starts at its link address (the boot loader maps it there).
- No text relocations (bionic refuses them).
- Every dynamic relocation inside .gamedata is R_ARM_RELATIVE. The bundle
  loader overwrites the region after the dynamic linker has run, and rebases
  only what the bundle records (link-time addresses), so a relocation against
  a symbol the dynamic linker resolves (a libc function, say) would be lost.
- Every undefined dynamic symbol is provided by one of the NDK libraries
  linked, and ld reported no unresolved reference (--link-log); the rest are
  what the shim or GPU layer still owes. They are written to --undefined-out
  either way.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

READELF = "arm-linux-gnueabi-readelf"
NM = "arm-linux-gnueabi-nm"


def run(*args: str) -> str:
    return subprocess.check_output(list(args), text=True, errors="ignore")


def load_segments(elf: Path) -> list[tuple[int, int]]:
    segs = []
    for line in run(READELF, "-l", "-W", str(elf)).splitlines():
        parts = line.split()
        if parts and parts[0] == "LOAD":
            segs.append((int(parts[2], 16), int(parts[5], 16)))
    if not segs:
        raise SystemExit("check_link: %s has no loadable segments" % elf)
    return segs


def section(elf: Path, name: str) -> tuple[str, int, int] | None:
    for line in run(READELF, "-S", "-W", str(elf)).splitlines():
        m = re.match(r"\s*\[\s*\d+\]\s+(\S+)\s+(\S+)\s+([0-9a-f]+)\s+[0-9a-f]+\s+([0-9a-f]+)", line)
        if m and m.group(1) == name:
            return m.group(2), int(m.group(3), 16), int(m.group(4), 16)
    return None


def span_header(elf: Path, out: Path) -> None:
    segs = load_segments(elf)
    low = min(s for s, _ in segs) & ~0xFFF
    high = max(s + n for s, n in segs)
    span = (high - low + 0xFFFFF) & ~0xFFFFF
    text = ("/* Generated by android/native/check_link.py from %s. */\n"
            "#define CTR_LOAD_ADDRESS 0x%08Xu\n#define CTR_LOAD_SPAN 0x%08Xu\n" % (elf.name, low, span))
    if not out.exists() or out.read_text() != text:
        out.write_text(text)


def check(args) -> int:
    problems: list[str] = []
    elf = args.elf

    segs = load_segments(elf)
    low = min(s for s, _ in segs)
    if low != args.load_address:
        problems.append("first segment at %#x, expected the load address %#x" % (low, args.load_address))
    high = max(s + n for s, n in segs)

    dynamic = run(READELF, "-d", "-W", str(elf))
    if "TEXTREL" in dynamic:
        problems.append("the library has text relocations")

    for path, want in ((elf, "NOBITS"), (args.image, "PROGBITS")):
        found = section(path, ".gamedata")
        if found is None or found[0] != want:
            problems.append("%s: .gamedata should be %s, is %s" % (path, want, found and found[0]))
    gd = section(elf, ".gamedata")
    if gd is not None:
        start, end = gd[1], gd[1] + gd[2]
        bad: dict[str, int] = {}
        relative = 0
        inside = False
        for line in run(READELF, "-r", "-W", str(elf)).splitlines():
            if line.startswith("Relocation section"):
                inside = "'.rel.dyn'" in line or "'.rel.plt'" in line
                continue
            m = re.match(r"^([0-9a-f]{8})\s+[0-9a-f]+\s+(R_ARM_\w+)\s*(\S*)", line) if inside else None
            if m and start <= int(m.group(1), 16) < end:
                if m.group(2) == "R_ARM_RELATIVE":
                    relative += 1
                else:
                    key = "%s %s" % (m.group(2), m.group(3))
                    bad[key] = bad.get(key, 0) + 1
        if bad:
            problems.append(".gamedata has %d symbol relocations the bundle cannot carry: %s"
                            % (sum(bad.values()), ", ".join(sorted(bad)[:20])))

    provided: set[str] = set()
    for lib in args.lib:
        path = args.ndk_lib / ("lib%s.so" % lib[2:] if lib.startswith("-l") else lib)
        for line in run(NM, "-D", "--defined-only", str(path)).splitlines():
            parts = line.split()
            if len(parts) >= 3:
                provided.add(parts[2].split("@")[0])
    undefined = set()
    for line in run(READELF, "--dyn-syms", "-W", str(elf)).splitlines():
        parts = line.split()
        if len(parts) >= 8 and parts[6] == "UND" and parts[4] != "WEAK":
            name = parts[7].split("@")[0]
            if name not in provided:
                undefined.add(name)
    if args.link_log and args.link_log.exists():
        # With --warn-unresolved-symbols the PIE link resolves what is missing
        # to 0 without a dynamic symbol; ld's warnings are the record.
        for m in re.finditer(r"undefined reference to [`']([^']+)'", args.link_log.read_text(errors="ignore")):
            undefined.add(m.group(1))
    if args.undefined_out:
        args.undefined_out.write_text("".join(n + "\n" for n in sorted(undefined)))
    if undefined:
        msg = "%d undefined symbols (shim/GPU/host still to provide), e.g. %s" % (
            len(undefined), ", ".join(sorted(undefined)[:15]))
        if args.allow_undefined:
            print("check_link: WARNING: " + msg, file=sys.stderr)
        else:
            problems.append(msg)

    if problems:
        for p in problems:
            print("check_link: " + p, file=sys.stderr)
        return 1
    print("check_link: %s at %#x..%#x, %d undefined" % (elf.name, low, high, len(undefined)))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--elf", type=Path, required=True)
    ap.add_argument("--image", type=Path)
    ap.add_argument("--span-header", type=Path)
    ap.add_argument("--load-address", type=lambda s: int(s, 0))
    ap.add_argument("--ndk-lib", type=Path)
    ap.add_argument("--lib", action="append", default=[])
    ap.add_argument("--undefined-out", type=Path)
    ap.add_argument("--link-log", type=Path, help="ld's output for the release link")
    ap.add_argument("--allow-undefined", action="store_true")
    args = ap.parse_args()
    if args.span_header:
        span_header(args.elf, args.span_header)
        return 0
    return check(args)


if __name__ == "__main__":
    sys.exit(main())
