#!/usr/bin/env python3
"""Generate the devkitPro tree origin's Makefile expects, for Android.

    gen_devkitpro.py --out DIR --ndk NDK --android-dir ANDROID [--tree TREE]

origin/3ds_port/Makefile and full.mk call $(DEVKITARM)/bin/arm-none-eabi-*,
$(DEVKITPRO)/tools/bin/picasso and read $(CTRULIB)/include; origin's Python
scripts call arm-none-eabi-{nm,readelf,objdump,objcopy} from $DEVKITARM/bin.
This writes those names as wrappers:

  devkitARM/bin/arm-none-eabi-gcc   NDK clang for armeabi-v7a (API 28), with
                                    the 3DS-only flags dropped and the shim,
                                    GPU and host include directories added
  devkitARM/bin/arm-none-eabi-{as,cpp,ld,nm,readelf,objcopy,objdump,ar,strip}
                                    GNU binutils for arm-linux-gnueabi
  tools/bin/picasso                 tools/picasso2glsl.py
  libctru/include, libctru/lib      empty: <3ds.h> comes from android/shim

Every path is absolute, so the wrappers work from any directory (the game
compile runs from the decomp root, the rest from 3ds_port).
"""

from __future__ import annotations

import argparse
import os
import shlex
import stat
import sys
from pathlib import Path

TARGET = "armv7a-linux-androideabi28"
BINUTILS_PREFIX = "arm-linux-gnueabi-"
BINUTILS = ["as", "cpp", "ld", "nm", "readelf", "objcopy", "objdump", "ar", "strip", "size"]

# Flags that only mean something to devkitARM: the ARM11's CPU and hard-float
# ABI (Android's armeabi-v7a is softfp), libctru's soft TLS and its link specs.
DROPPED = ["-march=armv6k", "-mtune=mpcore", "-mfloat-abi=hard", "-mtp=soft", "-mword-relocations"]
DROPPED_PREFIXES = ["-specs="]

# Always added. ARM state like origin's build (full.mk: "Game translation units
# are built in ARM state"). Position independent because the result is a
# shared object; definitions bind locally (the link uses -Bsymbolic too), so
# the PIC code reaches its own globals without the GOT.
#
# The -Wno-error= list covers diagnostics clang raises on origin's native
# units that GCC (origin's compiler) does not; they stay visible as warnings.
ADDED = [
    "--target=" + TARGET,
    "-marm",
    "-fPIC",
    "-fno-semantic-interposition",
]
CLANG_WARNINGS = [
    "-Wno-error=unknown-warning-option",
    "-Wno-error=unused-command-line-argument",
]


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    new = text.encode()
    if path.exists() and path.read_bytes() == new:
        return
    path.write_bytes(new)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def gcc_wrapper(clang: Path, includes: list[Path], extra: list[str]) -> str:
    drop_cases = "|".join(DROPPED + [p + "*" for p in DROPPED_PREFIXES])
    pre = " ".join(shlex.quote(a) for a in ADDED + CLANG_WARNINGS + extra)
    post = " ".join("-I" + shlex.quote(str(i)) for i in includes)
    return f"""#!/usr/bin/env bash
# Generated by android/toolchain/gen_devkitpro.py. Do not edit.
# arm-none-eabi-gcc for origin's Makefile: NDK clang for armeabi-v7a.
args=()
for a in "$@"; do
    case "$a" in
        {drop_cases}) ;;
        *) args+=("$a") ;;
    esac
done
exec {shlex.quote(str(clang))} {pre} "${{args[@]}}" {post}
"""


def binutils_wrapper(tool: str) -> str:
    return f"""#!/usr/bin/env bash
# Generated by android/toolchain/gen_devkitpro.py. Do not edit.
exec {BINUTILS_PREFIX}{tool} "$@"
"""


def picasso_wrapper(python: str, script: Path) -> str:
    return f"""#!/usr/bin/env bash
# Generated by android/toolchain/gen_devkitpro.py. Do not edit.
# picasso -o out.shbin in.v.pica: the PICA200 shader as a GLSL ES container.
exec {shlex.quote(python)} {shlex.quote(str(script))} "$@"
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, required=True, help="the fake DEVKITPRO directory")
    ap.add_argument("--ndk", type=Path, required=True)
    ap.add_argument("--android-dir", type=Path, required=True, help="the android/ directory (shim, gpu, host)")
    ap.add_argument("--picasso", type=Path, required=True, help="path of picasso2glsl.py")
    ap.add_argument("--compat-header", type=Path, default=None,
                    help="header force-included into every C compile")
    ap.add_argument("--python", default=sys.executable)
    args = ap.parse_args()

    out = args.out.resolve()
    ndk = args.ndk.resolve()
    clang = ndk / "toolchains" / "llvm" / "prebuilt" / "linux-x86_64" / "bin" / "clang"
    if not clang.exists():
        raise SystemExit("gen_devkitpro: no NDK clang at %s" % clang)
    for tool in BINUTILS:
        if not any((Path(d) / (BINUTILS_PREFIX + tool)).exists()
                   for d in os.environ.get("PATH", "").split(os.pathsep)):
            raise SystemExit("gen_devkitpro: %s%s not found (apt install binutils-arm-linux-gnueabi "
                             "gcc-arm-linux-gnueabi)" % (BINUTILS_PREFIX, tool))

    android = args.android_dir.resolve()
    includes = [android / "shim" / "include", android / "gpu" / "include", android / "host" / "include"]
    extra = []
    if args.compat_header is not None:
        extra += ["-include", str(args.compat_header.resolve())]

    bin_dir = out / "devkitARM" / "bin"
    write(bin_dir / "arm-none-eabi-gcc", gcc_wrapper(clang, includes, extra))
    for tool in BINUTILS:
        write(bin_dir / ("arm-none-eabi-" + tool), binutils_wrapper(tool))

    picasso = args.picasso.resolve()
    if not picasso.is_file():
        raise SystemExit("gen_devkitpro: required shader translator is missing: %s" % picasso)
    write(out / "tools" / "bin" / "picasso", picasso_wrapper(args.python, picasso))

    (out / "libctru" / "include").mkdir(parents=True, exist_ok=True)
    (out / "libctru" / "lib").mkdir(parents=True, exist_ok=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
