#pragma once
#include <3ds/types.h>
/* The Android shader container is generated by tools/picasso2glsl.py.
 * It deliberately has a distinct magic: a 3DS binary cannot be mistaken for GLSL. */
typedef struct { char name[64]; u32 index; } CtrShaderUniform;
typedef struct { char *source; unsigned uniformCount; CtrShaderUniform *uniforms; } DVLE_s;
typedef struct { unsigned numDVLE; DVLE_s *DVLE; } DVLB_s;
DVLB_s *DVLB_ParseFile(u32 *data, u32 size);
void DVLB_Free(DVLB_s *binary);
