org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Absolute path (or path relative to this directory) of the native build
# output: <nativeOut>/jniLibs/armeabi-v7a/libemerald.so and <nativeOut>/assets/romfs/**,
# written by tools/bootstrap.py --make. Override with -Pemerald.nativeOut=...
emerald.nativeOut=../../build/android-out
